### ISSUE TITLE
Y-axis Scrollbar problem

### ISSUE THREAD

**Issue by SiddhanthKapoor** [SeanLuis/rest-data-validator#23]
**Describe the bug**
The Website takes a little more than the viewport height of a laptop screen thus having a y-axis scrollbar which  looks unnecessary.

**Desktop:**
 - OS:  Windows
 - Browser : Chrome , Brave , Firefox

I would like to work on this issue , would love to hear back from you !

**Comment by SeanLuis** [comment]
Hi, thanks for the feedback. The issue you mention does not specifically belong to this repository, this is purely for the validation package.

@SiddhanthKapoor
