### ISSUE TITLE
Screen width between 600px to 700px does not show main screen of the website

### ISSUE THREAD

**Issue by SiddhanthKapoor** [SeanLuis/rest-data-validator#24]
**Describe the bug**
If a screen has a width between 600px to 700px , the hero element of the website is not available , this means for tablets the website is not even available

**To Reproduce**
1. Go to the website
2. Click on inspect
3. Select the responsive width to 650px

I would like to get this issue assigned to me and hear back from you.

**Comment by SeanLuis** [comment]
Hi, thanks for the feedback. The issue you mention does not specifically belong to this repository, this is purely for the validation package.

@SiddhanthKapoor
