### ISSUE TITLE
Copyright text Overlap

### ISSUE THREAD

**Issue by AnanteshG** [SeanLuis/rest-data-validator#25]
**Describe the bug**
The line of text before 'Copyright @ Sean Rodriguez' is overlapped with the div boxes.

**To Reproduce**
1. Go to Home Page
3. Scroll down to bottom

**Screenshots**
![{44FC8890-B15D-420B-9C32-A7D455C98CA7}](https://github.com/user-attachments/assets/948908da-453e-4884-bc9c-1ff5d69fdf8c)

**Comment by AnanteshG** [comment]
I would like to work on this issue.

**Comment by SeanLuis** [comment]
@AnanteshG 
Hi, thanks for the feedback. The issue you mention does not specifically belong to this repository, this is purely for the validation package.
